blank_issues_enabled: false
contact_links:
  - name: 💡 Ideas
    url: https://github.com/orgs/iptv-org/discussions/categories/ideas
    about: Share ideas for new features
  - name: 🙌 Show and tell
    url: https://github.com/orgs/iptv-org/discussions/categories/show-and-tell
    about: Show off something you've made
  - name: ❓ Q&A
    url: https://github.com/orgs/iptv-org/discussions/categories/q-a
    about: Ask the community for help
